/** Textos visíveis ao usuário — tom KISS, direto e confiável. */

export const PAGE_SUBTITLES = {
  dashboard: "Resumo do seu mês.",
  transactions: "Entradas, gastos e saldo.",
  cashflow: "Entradas, gastos e saldo do período.",
  goals: "Acompanhe o progresso das suas metas.",
  limits: "Defina limites simples por categoria.",
  investments: "Reservas e aplicações que você guardou.",
  reports: "Gastos por categoria e evolução do saldo.",
  categories: "Organize seus gastos por tipo.",
  assistant: "Pergunte sobre entradas, gastos e metas.",
  profile: "Dados da conta e preferências.",
} as const

export const NAV_LABELS = {
  dashboard: "Início",
  transactions: "Lançamentos",
  limits: "Limites",
  assistant: "Penny",
  cashflow: "Mês",
  goals: "Metas",
  investments: "Investimentos",
  reports: "Relatórios",
} as const

export const NAV_GROUPS = {
  hoje: "Hoje",
  planejar: "Planejar",
  investir: "Investir",
  entender: "Entender",
} as const

export const EMPTY_STATES = {
  transactions: {
    title: "Nenhum lançamento ainda.",
    description: "Adicione uma entrada ou um gasto para começar a acompanhar o mês.",
  },
  transactionsFiltered: {
    title: "Nenhum lançamento encontrado.",
    description: "Ajuste os filtros ou adicione um novo lançamento.",
  },
  goals: {
    title: "Nenhuma meta criada.",
    description: "Crie uma meta para acompanhar quanto guardar por mês.",
  },
  limits: {
    title: "Nenhum limite definido.",
    description: "Defina um limite por categoria para acompanhar os gastos do mês.",
  },
  investments: {
    title: "Nenhum investimento cadastrado.",
    description: "Registre reservas e aplicações para acompanhar o que você guardou.",
  },
  investmentsFiltered: {
    title: "Nenhum ativo encontrado.",
    description: "Ajuste os filtros para localizar um investimento.",
  },
  movements: {
    title: "Nenhum movimento registrado.",
    description: "Aportes e resgates aparecem aqui.",
  },
  reports: {
    title: "Ainda não há dados suficientes.",
    description: "Registre entradas e gastos para ver o resumo deste período.",
  },
  reportsExpenses: "Nenhum gasto para exibir neste período.",
  reportsLimits: "Nenhum limite definido para comparar.",
  reportsPortfolio: "Nenhum histórico de carteira para exibir.",
  penny: {
    title: "Como posso ajudar?",
    description: "Escolha uma sugestão ou escreva sua pergunta.",
  },
  pennyAnalysis: "Ainda não há dados suficientes para análise.",
  notifications: {
    title: "Nenhuma notificação.",
    description: "Alertas de limites, metas e lançamentos aparecem aqui.",
  },
} as const

export const TOAST = {
  success: {
    expenseSaved: "Gasto salvo.",
    incomeSaved: "Entrada adicionada.",
    transactionCreated: "Lançamento salvo.",
    transactionUpdated: "Lançamento atualizado.",
    transactionRemoved: "Lançamento excluído.",
    transactionsConfirmed: "Lançamentos confirmados.",
    transactionsOrganized: "Lançamentos organizados.",
    goalCreated: "Meta criada.",
    goalUpdated: "Meta atualizada.",
    goalRemoved: "Meta excluída.",
    goalContribution: "Aporte na meta registrado.",
    limitCreated: "Limite criado.",
    limitUpdated: "Limite atualizado.",
    limitRemoved: "Limite excluído.",
    investmentCreated: "Investimento cadastrado.",
    investmentUpdated: "Investimento atualizado.",
    investmentRemoved: "Investimento excluído.",
    incomeUpdated: "Renda atualizada.",
    categoryCreated: "Categoria criada.",
    subcategoryCreated: "Subcategoria criada.",
    categoryUpdated: "Categoria atualizada.",
    categoryRemoved: "Categoria excluída.",
    categoryHidden: "Categoria oculta.",
    subscriptionCreated: "Assinatura cadastrada.",
    subscriptionUpdated: "Assinatura atualizada.",
    subscriptionRemoved: "Assinatura removida.",
    installmentCreated: "Parcelamento cadastrado.",
    installmentUpdated: "Parcelamento atualizado.",
    installmentRemoved: "Parcelamento removido.",
    cardCreated: "Cartão cadastrado.",
    cardUpdated: "Cartão atualizado.",
    cardRemoved: "Cartão removido.",
    statementImported: "Extrato importado.",
    profileUpdated: "Perfil atualizado.",
    photoUpdated: "Foto de perfil atualizada.",
    passwordChanged: "Senha alterada.",
    demoRestored: "Demonstração restaurada.",
    sessionEnded: "Sessão encerrada.",
    onboardingDone: "Seu controle está pronto.",
    welcome: "Bem-vindo.",
    accountCreated: "Conta criada.",
    changesSaved: "Alterações salvas.",
  },
  error: {
    genericSave: "Não foi possível salvar agora. Tente novamente.",
    genericLoad: "Não conseguimos carregar seus dados. Atualize a página.",
    login: "Não foi possível entrar. Verifique e-mail e senha.",
    signup: "Não foi possível criar a conta. Tente novamente.",
    invalidFields: "Verifique os campos destacados.",
    invalidTransaction: "Verifique os dados do lançamento.",
    invalidGoal: "Verifique os dados da meta.",
    invalidLimit: "Verifique os dados do limite.",
    invalidInvestment: "Verifique os dados do investimento.",
    invalidIncome: "Informe um valor de renda maior que zero.",
    invalidAmount: "Informe um valor válido.",
    invalidImage: "Escolha um arquivo de imagem.",
    imageTooLarge: "A imagem deve ter no máximo 2 MB.",
    imageRead: "Não foi possível ler a imagem.",
    profileSave: "Não foi possível salvar o perfil.",
    photoSave: "Não foi possível salvar a foto.",
    emailNotFound: "E-mail não encontrado.",
    pennyResponse: "Não foi possível obter resposta da Penny. Tente novamente.",
    pennyQuery: "Não foi possível consultar a Penny. Tente novamente.",
    importEmpty: "Nenhum lançamento encontrado no extrato.",
    importProcess: "Não foi possível processar o extrato. Tente novamente.",
    wrongPassword: "Senha incorreta.",
    emailTaken: "Este e-mail já está cadastrado.",
    sessionMissing: "Sessão não encontrada.",
  },
} as const

export const ALERTS = {
  reviewTransactions: "Lançamentos para revisar",
  limitNear: "Perto do limite",
  limitExceeded: "Limite ultrapassado",
  goalAtRisk: "Meta em risco",
  goalDueSoon: "Meta perto do prazo",
  goalDone: "Meta concluída",
  subscriptionsSoon: "Cobranças nos próximos 7 dias",
  monthNegative: "Nesse ritmo, o mês fecha negativo",
  incomeNotRegistered: "Entrada principal não registrada",
  fixedExpensesHigh: "Compromissos fixos altos",
  lowMargin: "Pouco saldo disponível para novos gastos",
  extraIncome: "Entrada extra detectada",
  reserveBelowPlan: "Reserva abaixo do planejado",
  importPending: "Importação pendente",
  returnTarget: "Meta de rentabilidade atingida",
} as const

export const PENNY_STARTER_SUGGESTIONS = [
  "Quanto ainda posso gastar?",
  "Como está meu mês?",
  "Onde gastei mais este mês?",
  "Quais assinaturas pesam no mês?",
  "Resumo do mês",
  "Limites com minha renda",
  "Entrada extra conta no longo prazo?",
  "Como funcionam as categorias?",
  "O que os relatórios mostram?",
  "Minha meta cabe na renda?",
  "Quanto posso comprometer?",
  "Reserva e investimento no plano",
  "Como importar extrato?",
  "Quantos meses minha reserva cobre?",
  "Meus gastos vs 50/30/20?",
  "Este mês costuma ser mais caro?",
  "Tenho dinheiro parado?",
] as const

export const METRICS = {
  availableBalance: "Saldo disponível",
  monthIncome: "Entradas do mês",
  monthExpense: "Gastos do mês",
  accumulatedSavings: "Economia acumulada",
  income: "Entradas",
  expense: "Gastos",
} as const

export const TRANSACTION_TYPES = {
  expense: "Gasto",
  income: "Entrada",
  transfer: "Entre contas",
} as const

export const FORM = {
  newExpense: "Novo gasto",
  newIncome: "Nova entrada",
  newTransaction: "Novo lançamento",
  expenseAmount: "Valor gasto",
  incomeAmount: "Valor recebido",
  whereSpent: "Onde você gastou?",
  incomeSource: "Origem do dinheiro",
  paymentMethod: "Forma de pagamento",
  expenseDate: "Data do gasto",
  incomeDate: "Data do recebimento",
  category: "Categoria",
  goalName: "Nome da meta",
  goalTarget: "Valor desejado",
  goalDeadline: "Prazo",
  goalCurrent: "Valor guardado",
  limitAmount: "Quanto você quer gastar?",
  debtTotal: "Valor total",
  debtInstallment: "Valor da parcela",
  debtDueDate: "Data de vencimento",
  save: "Salvar",
  cancel: "Cancelar",
  edit: "Editar",
  delete: "Excluir",
  continue: "Continuar",
  startNow: "Começar agora",
} as const

export const HELP = {
  categories: "Use categorias para entender para onde seu dinheiro está indo.",
  limits: "Limites ajudam você a acompanhar os gastos antes do mês acabar.",
  goals: "A Penny calcula quanto você precisa guardar por mês para chegar no prazo.",
  debts: "Cadastre suas dívidas para entender quanto da sua renda já está comprometida.",
  incomeGeneral: "Vamos usar sua renda para calcular limites, metas e previsões.",
  incomeAdjustLater: "Você poderá ajustar isso depois.",
  moreRecords: "Quanto mais você registra, melhor fica sua visão financeira.",
} as const